# Generated by Django 5.0.6 on 2025-06-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('responsable', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('disponibilidad', models.JSONField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('AULA', 'Aula'), ('OTRO', 'Otro')], max_length=20)),
                ('capacidad', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10)),
                ('bloque_horario', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salon'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ALUMNO', 'Alumno')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('rol_destinatario', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ALUMNO', 'Alumno')], max_length=10)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
